name: pages-build-deployment

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          yarn install
      - name: Build
        run: |
          npx reveal-md lessons/ --static dist --static-dirs=plugins
          rsync -a -r lessons/ dist/
          cp -r plugins dist/_assets/
          cp -r .reveal-md dist/_assets/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
